# **1. EDA**

In [1]:
from pathlib import Path
import sys
import os
import pandas as pd

In [2]:
project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))
from src.load_data import load_data, get_data_info

## **1.1 File: domain_worker_desires.csv**

In [3]:
file_name = "domain_worker_desires.csv"
df_desire = load_data(file_name)

info = get_data_info(df_desire)
print("Thông tin DataFrame:")
print(info["shape"])
print(info["columns"])
print(info["missing_values"])

df_desire.head(5)

Thông tin DataFrame:
(5731, 31)
['Task ID', 'Occupation (O*NET-SOC Title)', 'Task', 'User ID', 'Date', 'Self-reported Expertise', 'Automation Desire Rating', 'Time', 'Core Skill Rating', 'Job Security Rating', 'Enjoyment Rating', 'Reasons for Automation Desire - Free Time', 'Reasons for Automation Desire - Repetitive', 'Reasons for Automation Desire - Human Error', 'Reasons for Automation Desire - Stress', 'Reasons for Automation Desire - Difficulty', 'Reasons for Automation Desire - Scale', 'Physical Action Requirement', 'Interpersonal Communication Requirement', 'Involved Uncertainty', 'Domain Expertise Requirement', 'Human Agency Scale Rating', 'Reasons for Human Agency - Physical', 'Reasons for Human Agency - Control', 'Reasons for Human Agency - Domain Knowledge', 'Reasons for Human Agency - Empathy', 'Reasons for Human Agency - Quality Oversight', 'Reasons for Human Agency - Dynamic', 'Reasons for Human Agency - Ethical', 'Other Reason for Automation Desire', 'Other Reason for Human Agency']
Task ID                                            0
Occupation (O*NET-SOC Title)                       0
Task                                               0
User ID                                            0
Date                                               0
Self-reported Expertise                            0
Automation Desire Rating                           0
Time                                               0
Core Skill Rating                                  0
Job Security Rating                                0
Enjoyment Rating                                   0
Reasons for Automation Desire - Free Time          0
Reasons for Automation Desire - Repetitive         0
Reasons for Automation Desire - Human Error        0
Reasons for Automation Desire - Stress             0
Reasons for Automation Desire - Difficulty         0
Reasons for Automation Desire - Scale              0
Physical Action Requirement                        0
Interpersonal Communication Requirement            0
Involved Uncertainty                               0
Domain Expertise Requirement                       0
Human Agency Scale Rating                          0
Reasons for Human Agency - Physical                0
Reasons for Human Agency - Control                 0
Reasons for Human Agency - Domain Knowledge        0
Reasons for Human Agency - Empathy                 0
Reasons for Human Agency - Quality Oversight       0
Reasons for Human Agency - Dynamic                 0
Reasons for Human Agency - Ethical                 0
Other Reason for Automation Desire              3585
Other Reason for Human Agency                   2959
dtype: int64

,Task ID,Occupation (O*NET-SOC Title),Task,User ID,Date,Self-reported Expertise,Automation Desire Rating,Time,Core Skill Rating,Job Security Rating,...,Human Agency Scale Rating,Reasons for Human Agency - Physical,Reasons for Human Agency - Control,Reasons for Human Agency - Domain Knowledge,Reasons for Human Agency - Empathy,Reasons for Human Agency - Quality Oversight,Reasons for Human Agency - Dynamic,Reasons for Human Agency - Ethical,Other Reason for Automation Desire,Other Reason for Human Agency
0,21520,Accountants and Auditors,Report to management regarding the finances of...,9aef09c6-ccfd-4dc0-a578-1ae21f7450a1,21/01/2025,Expert,4,1,3,3,...,5,True,True,True,True,True,True,True,NaN,NaN
1,21511,Accountants and Auditors,Examine and evaluate financial and information...,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Average,1,1,3,4,...,5,True,True,True,True,True,True,True,FALSE,NaN
2,21514,Accountants and Auditors,"Prepare, examine, or analyze accounting record...",9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Expert,1,4,4,1,...,5,True,True,True,True,True,True,True,FALSE,NaN
3,21515,Accountants and Auditors,Prepare adjusting journal entries.,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Average,1,1,4,1,...,5,True,True,True,True,True,True,True,FALSE,NaN
4,21516,Accountants and Auditors,Review accounts for discrepancies and reconcil...,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Expert,1,4,4,1,...,1,False,False,False,False,False,False,False,FALSE,FALSE

In [4]:
cols_to_check = [
    'Other Reason for Automation Desire', 
    'Other Reason for Human Agency'
]

info = get_data_info(df_desire, columns_to_check=cols_to_check)
for col, values in info["unique_values"].items():
    print(f"{col}: {values}")

Other Reason for Automation Desire: [nan, 'FALSE', 'Sometimes, without the tedious process, it is easy not to think about the necessity of costs, or to overlook things', 'this task used to be enjoyable but parents are difficult and students have been lazy in the last few years', "I prefer to do it myself cause monitoring employee's emotional behavior is critical ", 'it would allow me to focus on actual patient care. I would love to have epic that has developed the MY chart computer charting system incorpate a AI to do dicatation to the chart so that instead of typing I could talk to it to chart while actually actively doing the care on the patient and have more time for the much needed patients because in the hospitals most are under staffed and nurse are caring for more patients than they should so often when I was in the hospital setting I would get stuck after my shift at work charting for hours ', 'none', "I don't think it can take my job. If it can, then that AI system is my program", 'It is not my responsibility, but some time gets handed to me to focus on', 'There are many tasks that are mechanized, and or monotonous. Therefore, designing into the awareness of how to prevent such from affecting others is how we create the valuation. The valuation is confirmation.', 'It would help me to have more thorough notes  and allow me to be fully engaged in my meetings instead of worrying about getting all the information recorded. ', 'Only when the task is too difficult to be done manually or takes up too much time. ', 'I have too many other things to do, so it would help me get more things done.', 'ias. Using AI for Comp and Benefits Administration would diminish this sentiment.', 'if Ai Ai automates this task, it will free up my time to do more creative human centered tasks that would impact our security posture positively', 'AI could pull multiple sources and citations at once, as well as evaluate source quality', 'If AI could deal with customer complaints, then I could spend more time with happy customers. Let the unhappy people yell at AI.', 'I would like it to compile relevant information and bypass irrelevant information.', "It  depends on the purpose, but if one is  reading a drawing to manufacture  or analyze  the part, it would be very helpful. If instead the subsequent task is more complex, like understanding the part's function in a greater system, it would serve no purpose.", "I wouldn't have to work at all if AI was this good.", 'I would use an AI tool for an outage or service interuption, it could collate ALL the logs from the servers network devices and endpoints', 'There are already AI based tools for risk mitigation but are "applications" i think that generative AI could be a huge boost to this task', 'This task would be great at AI to compile the information across different vendors into one nice presentation. I still think the human element is important in this task.', 'Greater resource pool of research.', 'some of the question are simple and easily answered no need for me to answer they easy questions in person', 'To much at risk to automate entirely. AI can be leveraged only to an extent', 'I’d like AI to assist—not automate—my instructional design, improving efficiency while preserving quality. It could organize SME content, suggest approaches for complex concepts, and draft initial documentation for refinement. This would reduce repetitive tasks, letting me prioritize strategic decisions, creative problem-solving, and human-centered design. AI wouldn’t replace me but transform my role to emphasize higher-value work over basic content structuring.', 'I’d like AI to analyze learning outcomes, costs, and environmental impacts across training delivery modes, providing data-driven insights and comparison matrices from large datasets and benchmarks. I’d make final strategic decisions, factoring in culture, preferences, and constraints AI can’t judge. AI handles the heavy data lift; I interpret it contextually, blending analysis with my instructional expertise for smarter delivery choices.', 'I’d like AI to monitor training effectiveness by analyzing completion rates, scores, time metrics, and learner feedback across courses. It could create dashboards with trends and correlations, revealing what works best for different goals and groups. AI handles data crunching; I interpret patterns, contextualize insights, and refine designs—turning evaluation into ongoing, actionable improvements without the manual grind.', 'I’d like AI to evaluate training materials by checking readability, terminology consistency, objective alignment, and accessibility standards. This frees me to focus on nuanced aspects—contextual fit, cultural sensitivity, and strategic choices—requiring human judgment. AI handles systematic scans; I bring expertise to ensure materials meet learner needs and organizational context effectively.', 'I’d like AI to automate budget monitoring and reporting—a data-driven task needing precision, not creativity. AI could track costs, calculate per-learner metrics, and generate visual reports, flagging overruns early. This frees me from admin work to focus on strategic resource decisions and explaining investment impacts, while AI ensures accuracy and consistency.', 'Maybe to get ideas of what the AI would do.', 'Thinking about the story narrative is not my strong suit', 'You still need to experience getting feedback personally, thats the best way to learn. But AI can help streamline this.', 'I think the obtaining part is the part that would be best optimized by AI, as it could summarize the feedback gvien. ']
Other Reason for Human Agency: [nan, 'FALSE', 'All recons are different and could be quite complicated to figure out without background (which is sometimes only stored in human minds)', 'Cash flow must be considered when paying bills', 'legal concerns if not documented correctly and some situations are extremely random and not normal things so hard to intially put a dual legal ai and medical AI together to just do this alone but they would be of excellent value and reference to the nurses and doctors that have to make these reports', "the education is for the nurse and if the AI does the work and learning the nurse doesn't learn and so it would be a team effort", 'if drug counts and records are inaccurate this would flag a issue of possible diversion and the AI would need to be made to track that along with the other boring documentaion but again keep the standard of care and legal protection in check ', 'It needs through observation of AI application trend in different field', "In writing the proposal, I would like to tailor it to my own strengths and experiences, rather than using a generic approach that could apply to any researcher. Therefore, I believe it's important for me to be involved in shaping the direction of the proposal.", "You didn't say how competent the AI is.", 'NOTE: I have never done this task before, but the survey didnt let me continue without rating it since it was the only one avaliable. Please disregard my answers to all questions about "Investigate whether networks, workstations, the central processing unit of the system, or peripheral equipment are responding to a program\'s instructions" as they may impact the results of the survey ', 'There are often specific reasons for a company’s financial performance in certain areas, a company may have had a bad quarter on paper but they were changing a product offering or had a data breach. Interpersonal communication helps derive a better understanding of why this might have happened rather than automatically assuming the company did poorly. ', 'Company provided financials are subjected to Non-Disclosure Agreement, which is not allow to distribute on any outside platform. ', 'this task requires lived human experiences', 'No human wants AI to assign it work', 'Requires balancing technical facts with persuasive messaging.', 'Specifically, if pronouns &/or nicknames (pet names) need or not to be captured in the thanks ', 'I can navigate where there are uncertainty and critical decision making situations where AI cannot fully understand.Human-in-the-loop is needed for uncertainty.', 'Answer questions, customer emotions ', 'This task involves source-finding via confidential data pool', 'I would want to know the source of the information used for drafting or have some way to verify that. ', 'I’m thinking in particular about the reference interview aspects of the job', 'The task must be done with utmost security.', 'The goal of the task is constantly changing and need human to guild the AI. ', 'Human labor is essential to this type of work', 'decision making regarding what is important and needs to be sent and what does not', 'If there are multiple errors in payroll, the corrections can be worse than the checking and employees get very angry when you mess with their money.', 'AI should only be used for touchups really, not to create AN ENTIRE IMAGE from scratch.', 'The tasks require subjective creative expertise AI cannot replicate', "Writing captures many emotions. Words and they're definitions don't begin to capture it. AI would struggle to meet demands of authors emotional stories.", 'Other', 'cash payments', "i do not trust ai with people's personally identifiable information, like payment info", "when conducting literature reviews, you may not even know what  you don't know. As you find resources, that can change the direction of future research. I wouldn't let AI take total control on changing the topic of my research", '"Reviewing the work by other writers" requires making clear decisions about quality. Oversight is very important.', 'My input is vital because instructional design goes beyond organizing content—it requires strategic decisions aligning with learning goals and audience needs. I bring expertise in adult learning, scaffolding complex concepts, and anticipating struggles. While AI can draft and structure, it misses organizational context and nuance. My judgment ensures accuracy, accessibility, and creative, human-centered design that makes learning effective, not just informative.', 'My input is crucial for evaluating training delivery modes beyond data analysis. While AI can crunch metrics and costs, I interpret them within organizational contexts—culture, stakeholder priorities, and constraints. My experience anticipates resistance, ensures learning transfer, and balances budget, effectiveness, and readiness. I make strategic, nuanced decisions AI can’t, drawing on years of instructional design wisdom across diverse settings.', 'My input is essential for evaluating training effectiveness beyond data processing. I define metrics aligning with goals, interpret results contextually—e.g., when 70% completion is success or not—and spot strategy-outcome links AI might miss. I turn insights into practical design fixes, factoring in organizational dynamics and stakeholder needs AI can’t grasp, ensuring meaningful, actionable improvements.', 'My input is vital for designing training because it demands strategic vision and human-centered thinking AI can’t match. I uncover true business needs, tailor experiences to organizational cultures, balance priorities like depth versus efficiency, and craft authentic scenarios. My judgment integrates politics, culture, and realities AI can’t see, ensuring training aligns with outcomes and resonates with learners.', 'My input is crucial for developing alternative training methods because it involves diagnosing root causes—content, delivery, readiness, or barriers—beyond just suggesting options. I interpret data contextually, gather nuanced feedback, and match strategies to challenges, drawing on experience AI can’t replicate. My contextual insight ensures viable, sustainable solutions tailored to organizational constraints and cultures.', 'My input is essential for evaluating training materials beyond standardized checks. I assess scaffolding for learner needs, spot missed opportunities for deeper understanding, and catch cultural or contextual issues AI might overlook. My experience ensures tone, detail, and examples fit the audience, drawing on practical judgment that exceeds codified criteria.', 'Balancing is a creative process that often depends on the overall tone and pacing of the game. AI can assist, but I need to guide it to match my design vision.', 'It is a very creative process; if AI were to be used it would be only to provide inspiration and not to do any of the writing. I would prefer to do 100% of the writing by myself as I really love creative writing.', 'The balancing can be automated, but will require constant tweaking after play testing.', "I've tested AI logic for games, and they requrie a fair amount of effort to ensure that game play mechanics work with out bugs.", 'Still requires moderate game play testing, and to ensure that story lines are cohesive', 'This question is just the others, just the inverse, except the responsibility of review quality is on you.', 'I have found AI is incapable of creativity, this task requires creative ideas. ', 'The implementation of feedback would certainly need to be handled mostly by a person. ', 'Security issues that happen in real life can range from a non-urgent dependency version update to a full-on data breach or DDoS attack. If we want to automate the changes would need to be incremental and carefully carried out with human expert supervision.']

## **1.2 File domain_worker_metadatacsv**

In [5]:
file_name = "domain_worker_metadata.csv"
df_metadata = load_data(file_name)

info = get_data_info(df_metadata)
print("Thông tin DataFrame:")
print(info["shape"])
print(info["columns"])
print(info["missing_values"])

df_metadata.head(5)

Thông tin DataFrame:
(1500, 26)
['User ID', 'Occupation (O*NET-SOC Title)', 'Gender', 'Race', 'Income', 'Age', 'Education', 'Experience', 'AI Tedious Work Attitude', 'AI Job Importance Attitude', 'AI Daily Interest Attitude', 'AI Suffering Attitude', 'Zip Code', 'Political Affiliation', 'LLM Familiarity', 'LLM Use in Work', 'LLM Usage by Type - Information Access', 'LLM Usage by Type - Edit', 'LLM Usage by Type - Idea Generation', 'LLM Usage by Type - Communication', 'LLM Usage by Type - Analysis', 'LLM Usage by Type - Decision', 'LLM Usage by Type - Coding', 'LLM Usage by Type - System Design', 'LLM Usage by Type - Data Processing', 'Recruitment Source']
User ID                                     0
Occupation (O*NET-SOC Title)                0
Gender                                      0
Race                                        0
Income                                      0
Age                                         0
Education                                   0
Experience                                  0
AI Tedious Work Attitude                    0
AI Job Importance Attitude                  0
AI Daily Interest Attitude                  0
AI Suffering Attitude                       0
Zip Code                                  802
Political Affiliation                       0
LLM Familiarity                             0
LLM Use in Work                             0
LLM Usage by Type - Information Access    272
LLM Usage by Type - Edit                  272
LLM Usage by Type - Idea Generation       272
LLM Usage by Type - Communication         272
LLM Usage by Type - Analysis              272
LLM Usage by Type - Decision              272
LLM Usage by Type - Coding                272
LLM Usage by Type - System Design         272
LLM Usage by Type - Data Processing       272
Recruitment Source                          0
dtype: int64

,User ID,Occupation (O*NET-SOC Title),Gender,Race,Income,Age,Education,Experience,AI Tedious Work Attitude,AI Job Importance Attitude,...,LLM Usage by Type - Information Access,LLM Usage by Type - Edit,LLM Usage by Type - Idea Generation,LLM Usage by Type - Communication,LLM Usage by Type - Analysis,LLM Usage by Type - Decision,LLM Usage by Type - Coding,LLM Usage by Type - System Design,LLM Usage by Type - Data Processing,Recruitment Source
0,a17b322e-3134-475c-a652-89f27b3a9946,Medical and Health Services Managers,Female,White,60-86K,30,"Professional Degree (e.g., MD, JD)",1-2 year,Somewhat agree,Neither agree nor disagree,...,Daily,Never,Never,Never,Weekly,Weekly,Never,Never,Monthly,Prolific
1,533a6bf0-9958-4892-8777-44108350b9be,Customer Service Representatives,Male,Asian American and Pacific Islander,86K-165K,28,Bachelor’s Degree,6-10 years,Somewhat agree,Somewhat agree,...,Weekly,Weekly,Daily,Daily,Weekly,Daily,Weekly,Never,Weekly,Prolific
2,9f48da63-2e55-413d-a8b4-ec18e410eb36,Mechanical Engineers,Male,Black,30-60K,34,Bachelor’s Degree,6-10 years,Strongly agree,Strongly agree,...,Weekly,Daily,Daily,Daily,Daily,Daily,Never,Never,Never,Prolific
3,32176135-796f-4d69-811a-b26a9dfc0c3c,Editors,Female,White,60-86K,53,Bachelor’s Degree,More than 10 years,Somewhat agree,Neither agree nor disagree,...,Never,Monthly,Never,Never,Never,Never,Never,Never,Never,Prolific
4,f5ebd9c8-d0f3-4e08-8027-5680268d073d,Computer Network Support Specialists,Male,White,86K-165K,39,Bachelor’s Degree,6-10 years,Somewhat agree,Somewhat agree,...,Weekly,Weekly,Monthly,Daily,Daily,Daily,Weekly,Weekly,Weekly,Prolific

In [6]:
cols_to_check = [
    'Zip Code', 
    'LLM Usage by Type - Information Access',
    'LLM Usage by Type - Edit',
    'LLM Usage by Type - Idea Generation',
    'LLM Usage by Type - Communication',
    'LLM Usage by Type - Analysis',
    'LLM Usage by Type - Decision',
    'LLM Usage by Type - Coding',
    'LLM Usage by Type - System Design',
    'LLM Usage by Type - Data Processing'
]

info = get_data_info(df_metadata, columns_to_check=cols_to_check)
for col, values in info["unique_values"].items():
    print(f"{col}: {values}")

Zip Code: [nan, '10010', '6438', '22043', '7207', '2155', '96789', '23919', '21203', '90001', '77642', '80010', '46219', '33189', '75001', '30121', '97266', '24012', '53217', '72120', '80126', '40213', '60618', '80013', '63133', '94513', '84088', '28079', '39759', '43701', '53821', '19131', '92092', '15232', '900105', '100001', '15650', '14616', '14623', '30067', '77034', '90012', '55420', '27101', '48225', '24201', '32226', '44107', '72342', '60613', '39560', '33167', '93401', '11236', '7087', '79901', '33029', '23294', '92551', '77840', '60656', '33917', '92392', '38506', '17044', '82520', '10583', '75407', '60046', '78636', '97527', '14883', '2904', '54449', '30303', '10001', '10002', '37862', '15524', '21043', '40515', '27574', '80634', '94901', '17353', '77297', '10454', '10031', '98223', '92627', '40475', '30213', '18301', '89104', '75241', '35216', '44612', '1864', '77009', '71049', '52632', '29303', '53703', '10023', '36551', '92865', '19809', '8089', '60459', '30312', '25304', '48185', '90731', '47130', '88001', '92591', '24148', '85304', '33809', '31535', '95111', '37211', '39160', '72206', '20148', '45230', '27317', '26764', '96084', '20149', '77494', '32601', '87508', '85013', '90715', '43230', '900001', '8000', '75063', '10041', '20186', '33605', '30030', '37917', '75104', '30506', '33759', '37601', '33578', '3103', '37066', '43311', '10009', '55414', '45255', '94025', '61605', '8230', '30302', '68102', '75007', '44313', '68501', '53215', '47421', '29036', '93276', '63801', '31093', '96047', '19444', '14870', '59601', '28601', '10042', '34474', '12992', '78239', '89130', '77006', '60156', '85043', '77026', '68154', '90601', '30274', '32095', '78070', '95112', '40903', '92630', '85743', '80017', '42262', '11746', '60622', '27215', '60914', '23454', '10473', '19130', '27587', '64145', '27616', '15728', '5001', '10012', '43201', '27882', '70812', '34683', '11763', '28152', '32808', '74501', '10006', '92109', '60637', '28607', '53115', '32792', '34762', '78415', '62203', '32708', '45239', '40223', '55406', '11727', '74103', '87106', '19104', '94306', '30031', '900101', '99101', '85282', '6382', '55130', '30519', '29505', '54901', '73069', '83404', '96701', '39553', '96816', '98661', '91436', '7030', '97367', '76012', '79936', '70775', '37912', '85383', '24015', '47060', '59427', '33913', '35563', '77028', '11201', '89115', '55313', '48168', '30236', '22755', '30501', '66224', '94109', '49684', '29212', '80211', '42327', '77023', '63020', '45213', '11221', '34109', '44111', '77041', '92679', '10282', '1468', '55347', '68771', '22911', '22079', '29617', '55901', '41311', '60620', '32814', '29412', '33133', '6040', '83686', '37129', '77075', '32204', '92677', '30034', '89128', '13782', '34638', '49047', '18224', '36117', '50401', '87507', '72019', '54022', '44883', '7017', '33755', '90004', '33071', '78260', '64034', '40021', '73003', '16743', '96744', '33161', '27107', '75006', '24112', '45218', '72476', '53208', '16648', '19128', '92029', '75503', '47265', '22305', '98360', '71040', '98102', '23832', '27527', '32082', '11217', '67207', '76020', '38111', '44240', '32955', '28139', '23831', '79413', '18403', '24701', '77401', '74839', '30339', '71854', '48231', '31805', '32224', '74015', '30110', '19707', '10022', '75771', '72204', '19020', '66212', '95818', '6112', '55419', '20103', '81050', '27893', '72921', '31773', '29223', '43512', '35760', '43228', '23608', '18337', '37013', '40220', '28412', '92336', '98674', '17519', '20175', '35405', '30011', '78247', '46825', '2135', '10030', '36535', '83646', '49849', '55306', '68516', '28054', '28213', '75050', '51503', '45895', '77591', '60504', '44030', '98005', '14626', '10591', '55068', '62650', '98226', '94043', '77036', '95350', '96706', '72076', '94305', '86404', '65616', '55104', '100266', '22656', '46143', '18104', '93720', '40204', '38104', '72740', '84108', '43202', '77095', '28262', '33880', '418', '48238', '11720', '2142', '97404', '8400', '58601', '38501', '64772', '66614', '64129', '98294', '78410', '37363', '84104', '98229', '80602', '54311', '7871', '78749', '94501', '27705', '35233', '93036', '94304', '94158', '21230', '4348', '10067', '29730', '10027', '1109', '10985', '77025', '54017', '10024', '29625', '33442', '28105', '63146', '95050', '76116', '78043', '57103', '11373', '78418', '34787', '6010', '77364', '22203', '30363', '84025', '15021', '62869', '93309', '90028', '55408', '24445', '22033', '75201', '94024', '90007', '39202', '11211', '75126', '85339', '44067', '95051', '95014', '58201', '11105', '33614', '8901', '95123', '85255', '85249', '8753', '78202', '75240', '79606', '80022', '28612', '85023-6767', '94520', '96734', '11385', '30338', '77493', '27520', '92129', '85310', '2128', '14513', '18612', '4106', '65203', '72034', '28269', '33772', '94536', '90024', '19475', '21061', '29732', '90046', '19106', '94087', '10471', '96826', '32826', '70128', '84315', '46989', '84098', '2446', '91381', '60115', '98266', '84062', '33415', '64132', '2134', '18704', '28020', '234', '48187', '94110', '94010', '95129', '94401', '92264', '90015', '30815', '19606', '37303', '38559', '28715', '49036', '75211', '46060', '30040', '77045', '75460', '90189', '95831', '1830', '45385', '67212', '32023', '2351', '53714', '75013', '50011', '32720', '34431', '95682', '94114', '39452', '21788', '66012', '70454', '95502', '93609', '93277', '19148', '15425', '98908', '100037', '16801', '35000', '6762', '99507', '29449', '60016', '33170', '8873', '72704', '94117', '11234', '7008', '19973', '92240', '43055', '64836', '29902', '50263', '29687', '43054', '17403', '32533', '95134', '48105', '8602', '48154', '94086', '89145', '40744', '30458', '70586', '28351', '83805', '47712', '48075', '98201']
LLM Usage by Type - Information Access: ['Daily', 'Weekly', 'Never', 'Monthly', nan]
LLM Usage by Type - Edit: ['Never', 'Weekly', 'Daily', 'Monthly', nan]
LLM Usage by Type - Idea Generation: ['Never', 'Daily', 'Monthly', 'Weekly', nan]
LLM Usage by Type - Communication: ['Never', 'Daily', 'Weekly', 'Monthly', nan]
LLM Usage by Type - Analysis: ['Weekly', 'Daily', 'Never', 'Monthly', nan]
LLM Usage by Type - Decision: ['Weekly', 'Daily', 'Never', 'Monthly', nan]
LLM Usage by Type - Coding: ['Never', 'Weekly', 'Daily', 'Monthly', nan]
LLM Usage by Type - System Design: ['Never', 'Weekly', 'Daily', 'Monthly', nan]
LLM Usage by Type - Data Processing: ['Monthly', 'Weekly', 'Never', 'Daily', nan]

## **1.3 file expert_rated_technological_capability.csv**

In [7]:
file_name = "expert_rated_technological_capability.csv"
df_expert = load_data(file_name)

info = get_data_info(df_expert)
print("Thông tin DataFrame:")
print(info["shape"])
print(info["columns"])
print(info["missing_values"])

df_desire.head(5)

Thông tin DataFrame:
(2057, 11)
['Task ID', 'Occupation (O*NET-SOC Title)', 'Task', 'User ID', 'Date', 'Automation Capacity Rating', 'Physical Action Requirement', 'Involved Uncertainty', 'Domain Expertise Requirement', 'Interpersonal Communication Requirement', 'Human Agency Scale Rating']
Task ID                                    0
Occupation (O*NET-SOC Title)               0
Task                                       0
User ID                                    0
Date                                       0
Automation Capacity Rating                 0
Physical Action Requirement                0
Involved Uncertainty                       0
Domain Expertise Requirement               0
Interpersonal Communication Requirement    0
Human Agency Scale Rating                  0
dtype: int64

,Task ID,Occupation (O*NET-SOC Title),Task,User ID,Date,Self-reported Expertise,Automation Desire Rating,Time,Core Skill Rating,Job Security Rating,...,Human Agency Scale Rating,Reasons for Human Agency - Physical,Reasons for Human Agency - Control,Reasons for Human Agency - Domain Knowledge,Reasons for Human Agency - Empathy,Reasons for Human Agency - Quality Oversight,Reasons for Human Agency - Dynamic,Reasons for Human Agency - Ethical,Other Reason for Automation Desire,Other Reason for Human Agency
0,21520,Accountants and Auditors,Report to management regarding the finances of...,9aef09c6-ccfd-4dc0-a578-1ae21f7450a1,21/01/2025,Expert,4,1,3,3,...,5,True,True,True,True,True,True,True,NaN,NaN
1,21511,Accountants and Auditors,Examine and evaluate financial and information...,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Average,1,1,3,4,...,5,True,True,True,True,True,True,True,FALSE,NaN
2,21514,Accountants and Auditors,"Prepare, examine, or analyze accounting record...",9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Expert,1,4,4,1,...,5,True,True,True,True,True,True,True,FALSE,NaN
3,21515,Accountants and Auditors,Prepare adjusting journal entries.,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Average,1,1,4,1,...,5,True,True,True,True,True,True,True,FALSE,NaN
4,21516,Accountants and Auditors,Review accounts for discrepancies and reconcil...,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Expert,1,4,4,1,...,1,False,False,False,False,False,False,False,FALSE,FALSE

## **1.4 File task_statement_with_metadata.csv**

In [8]:
file_name = "task_statement_with_metadata.csv"
df_task = load_data(file_name)

info = get_data_info(df_task)
print("Thông tin DataFrame:")
print(info["shape"])
print(info["columns"])
print(info["missing_values"])

df_desire.head(5)

Thông tin DataFrame:
(2131, 14)
['O*NET-SOC Code', 'Occupation (O*NET-SOC Title)', 'Task ID', 'Task', 'Task Type', 'Date', 'Category', 'Frequency', 'Importance', 'Relevance', 'Occupation Mean Annual Wage', 'Occupation Employment', 'Skill (O*NET Work Activity)', 'Skill ID (O*NET Generalized Work Activity ID)']
O*NET-SOC Code                                     0
Occupation (O*NET-SOC Title)                       0
Task ID                                            0
Task                                               0
Task Type                                          0
Date                                               0
Category                                           0
Frequency                                          0
Importance                                         0
Relevance                                          0
Occupation Mean Annual Wage                      642
Occupation Employment                            642
Skill (O*NET Work Activity)                        0
Skill ID (O*NET Generalized Work Activity ID)      0
dtype: int64

,Task ID,Occupation (O*NET-SOC Title),Task,User ID,Date,Self-reported Expertise,Automation Desire Rating,Time,Core Skill Rating,Job Security Rating,...,Human Agency Scale Rating,Reasons for Human Agency - Physical,Reasons for Human Agency - Control,Reasons for Human Agency - Domain Knowledge,Reasons for Human Agency - Empathy,Reasons for Human Agency - Quality Oversight,Reasons for Human Agency - Dynamic,Reasons for Human Agency - Ethical,Other Reason for Automation Desire,Other Reason for Human Agency
0,21520,Accountants and Auditors,Report to management regarding the finances of...,9aef09c6-ccfd-4dc0-a578-1ae21f7450a1,21/01/2025,Expert,4,1,3,3,...,5,True,True,True,True,True,True,True,NaN,NaN
1,21511,Accountants and Auditors,Examine and evaluate financial and information...,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Average,1,1,3,4,...,5,True,True,True,True,True,True,True,FALSE,NaN
2,21514,Accountants and Auditors,"Prepare, examine, or analyze accounting record...",9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Expert,1,4,4,1,...,5,True,True,True,True,True,True,True,FALSE,NaN
3,21515,Accountants and Auditors,Prepare adjusting journal entries.,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Average,1,1,4,1,...,5,True,True,True,True,True,True,True,FALSE,NaN
4,21516,Accountants and Auditors,Review accounts for discrepancies and reconcil...,9ee73f2c-d7a0-4f7f-be1c-a2a0477c8d09,04/02/2025,Expert,1,4,4,1,...,1,False,False,False,False,False,False,False,FALSE,FALSE

In [9]:
cols_to_check = [
    'Occupation Mean Annual Wage ', 
    'Occupation Employment'
]

info = get_data_info(df_task, columns_to_check=cols_to_check)
for col, values in info["unique_values"].items():
    print(f"{col}: {values}")

Occupation Employment: [21100.0, 384980.0, 254140.0, 645970.0, 818620.0, nan, 81240.0, 20070.0, 215520.0, 44960.0, 176420.0, 210340.0, 565840.0, 100870.0, 305020.0, 7790.0, 397770.0, 219530.0, 917460.0, 235640.0, 893900.0, 105930.0, 102370.0, 436610.0, 861140.0, 1448290.0, 47170.0, 67370.0, 270480.0, 107820.0, 62830.0, 28110.0, 290530.0, 53530.0, 73570.0, 497800.0, 179430.0, 38480.0, 146450.0, 697210.0, 177010.0, 73180.0, 64770.0, 318570.0, 109870.0, 199800.0, 78860.0, 28340.0, 2220.0, 107760.0, 29800.0, 111140.0, 12790.0, 53080.0, 68440.0, 21860.0, 20330.0, 355410.0, 75710.0, 188790.0, 93940.0, 37950.0, 23220.0, 350230.0, 8440.0, 22770.0, 286760.0, 6770.0, 14740.0, 18970.0, 109550.0, 20020.0, 39900.0, 9060.0, 62130.0, 92710.0, 14680.0, 12500.0, 73410.0, 37450.0, 56720.0, 34520.0, 19760.0, 11460.0, 156300.0, 1560.0, 21340.0, 8780.0, 83250.0, 8330.0, 84930.0, 22510.0, 5720.0, 15880.0, 7720.0, 2950.0, 43040.0, 1380.0, 3140.0, 5950.0, 39390.0, 5990.0, 32940.0, 19450.0, 747750.0, 13220.0, 16230.0, 367220.0, 48170.0, 81780.0, 36240.0, 48820.0, 9120.0, 39910.0, 11480.0, 7130.0, 13590.0, 12420.0, 3290.0, 17170.0, 59090.0, 4100.0, 22800.0, 29260.0, 111150.0, 7050.0, 131830.0, 73770.0, 50370.0, 21280.0, 30250.0, 214260.0, 145270.0, 23880.0, 41550.0, 280590.0, 95480.0, 55530.0, 47800.0, 12630.0, 70080.0, 21080.0, 13050.0, 51230.0, 28860.0, 18700.0, 26290.0, 16960.0, 223460.0, 41530.0, 43070.0, 10000.0, 472300.0, 59150.0, 293930.0, 66430.0, 1495580.0, 165020.0, 417500.0, 1455770.0, 156950.0, 59900.0, 40090.0, 6260.0, 170010.0, 11960.0, 2725930.0, 156260.0, 80070.0, 173100.0, 38030.0, 83420.0, 92580.0, 127440.0, 101140.0, 211000.0, 385000.0, 49720.0, 472770.0, 154540.0, 830760.0, 1737820.0, 135280.0, 36030.0, 4000.0, 229070.0, 2510550.0, 5160.0, 5900.0, 73010.0, 20900.0, 59990.0, 23070.0, 9180.0, 32150.0, 176950.0, 28230.0, 22400.0]